export const products = [
  {
    id: "nebula-x1",
    slug: "nebula-x1",
    name: "Nebula X1 Pro",
    short: "Màn 6.7 inch, chip Aether 9, camera 108MP.",
    description:
      "Nebula X1 Pro là chiếc flagship tập trung trải nghiệm hình ảnh sắc nét và hiệu năng ổn định cả ngày. Khung hợp kim siêu nhẹ, màn hình 120Hz và pin 5200mAh.",
    price: 28990000,
    salePrice: 25990000,
    badge: "Flagship",
    brand: "Nebula",
    category: "Smartphone",
    rating: 4.8,
    reviewCount: 128,
    stock: 12,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.7 inch OLED 120Hz",
      Chip: "Aether 9",
      RAM: "12GB",
      Storage: "256GB",
      Battery: "5200mAh",
      Camera: "108MP + 50MP + 12MP",
    },
  },
  {
    id: "nova-slim",
    slug: "nova-slim",
    name: "Nova Slim 5G",
    short: "Siêu mỏng 7.1mm, pin 4800mAh.",
    description:
      "Nova Slim 5G tập trung vào thiết kế tối giản, gọn nhẹ nhưng vẫn đủ pin cho cả ngày. Hỗ trợ sạc nhanh 66W.",
    price: 15990000,
    salePrice: 14990000,
    badge: "Thiết kế",
    brand: "Nova",
    category: "Smartphone",
    rating: 4.5,
    reviewCount: 64,
    stock: 24,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.4 inch AMOLED 90Hz",
      Chip: "Helio Z5",
      RAM: "8GB",
      Storage: "256GB",
      Battery: "4800mAh",
      Camera: "64MP + 12MP",
    },
  },
  {
    id: "orbit-play",
    slug: "orbit-play",
    name: "Orbit Play Max",
    short: "Tản nhiệt buồng hơi, chơi game 120fps.",
    description:
      "Orbit Play Max dành cho game thủ với tản nhiệt buồng hơi, loa stereo lớn và chế độ hiệu năng tăng cường.",
    price: 20990000,
    salePrice: 19990000,
    badge: "Gaming",
    brand: "Orbit",
    category: "Gaming",
    rating: 4.7,
    reviewCount: 92,
    stock: 18,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.8 inch OLED 144Hz",
      Chip: "Vortex X",
      RAM: "16GB",
      Storage: "512GB",
      Battery: "6000mAh",
      Camera: "50MP + 13MP",
    },
  },
  {
    id: "luma-lite",
    slug: "luma-lite",
    name: "Luma Lite",
    short: "Gọn nhẹ, giá tốt, camera AI.",
    description:
      "Luma Lite cân bằng giữa giá thành và trải nghiệm. Camera AI và màn hình 90Hz giúp mọi thao tác mượt mà.",
    price: 7990000,
    salePrice: 6990000,
    badge: "Giá tốt",
    brand: "Luma",
    category: "Popular",
    rating: 4.3,
    reviewCount: 51,
    stock: 40,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.5 inch LCD 90Hz",
      Chip: "Pulse A1",
      RAM: "6GB",
      Storage: "128GB",
      Battery: "5000mAh",
      Camera: "50MP + 8MP",
    },
  },
  {
    id: "zen-compact",
    slug: "zen-compact",
    name: "Zen Compact",
    short: "Máy nhỏ gọn, tối ưu một tay.",
    description:
      "Zen Compact dành cho người thích gọn nhẹ. Vẫn giữ được pin 4500mAh và chip tiết kiệm điện.",
    price: 10990000,
    salePrice: 9990000,
    badge: "Compact",
    brand: "Zen",
    category: "Compact",
    rating: 4.2,
    reviewCount: 34,
    stock: 15,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.1 inch OLED",
      Chip: "Zenith S",
      RAM: "8GB",
      Storage: "128GB",
      Battery: "4500mAh",
      Camera: "48MP + 12MP",
    },
  },
  {
    id: "pulse-note",
    slug: "pulse-note",
    name: "Pulse Note+",
    short: "Bút cảm ứng, ghi chú nhanh.",
    description:
      "Pulse Note+ hỗ trợ bút cảm ứng để ghi chú, phác thảo và làm việc nhanh. Màn hình lớn 6.9 inch.",
    price: 18990000,
    salePrice: 17990000,
    badge: "Work",
    brand: "Pulse",
    category: "Productivity",
    rating: 4.6,
    reviewCount: 70,
    stock: 10,
    image: "/phone-shell.svg",
    specs: {
      Screen: "6.9 inch OLED 120Hz",
      Chip: "Focus M2",
      RAM: "12GB",
      Storage: "256GB",
      Battery: "5400mAh",
      Camera: "50MP + 50MP",
    },
  },
];

export const categories = [
  { name: "Flagship", description: "Sức mạnh & camera tốt nhất." },
  { name: "Gaming", description: "Tản nhiệt mạnh, màn hình 144Hz." },
  { name: "Popular", description: "Cân bằng giá & trải nghiệm." },
  { name: "Compact", description: "Gọn nhẹ, tiện thao tác." },
  { name: "Productivity", description: "Làm việc, ghi chú nhanh." },
];

